CREATE BIGFILE TABLESPACE CMX_DATA NOLOGGING DATAFILE  'C:/app/stelukut/MDM/CMX_DATA1.dbf' SIZE 2048M REUSE EXTENT MANAGEMENT LOCAL;
CREATE BIGFILE TABLESPACE CMX_INDX NOLOGGING DATAFILE 'C:/app/stelukut/MDM/CMX_INDX1.dbf' SIZE 2048M REUSE EXTENT MANAGEMENT LOCAL;
CREATE BIGFILE TABLESPACE CMX_TEMP NOLOGGING DATAFILE 'C:/app/stelukut/MDM/CMX_TEMP1.dbf' SIZE 2048M REUSE EXTENT MANAGEMENT LOCAL;

